- components/hd44780/hd44780.c
Without this fix GPIO_NUM_32 and bigger are truncated to GPIO_NUM_0.
> Fix for 64 bit integers.

- components/bmp280/bmp280.c
helps debugging funky issues (especially on a breadboard).
while here, use consistent error messages
> bmp280: show chip ID detected when the ID is not expected one

- components/tsl2561/tsl2561.c
- examples/tsl2561/README.md
- examples/tsl2561/main/main.c
with 410 ms, my sensor does not return valid values.
here is the log.
```
D (8216) TSL2561: integration time: 410 ms channel0: 0x0 channel1: 0x0
Lux: 0
```
```
D (7706) TSL2561: integration time: 415 ms channel0: 0x0 channel1: 0x0
Lux: 0
```
```
D (5236) TSL2561: integration time: 420 ms channel0: 0x1992 channel1: 0xa6e
Lux: 1324
```
> support ESP8266 and increase sleep time in get_channel_data()

- .travis.yml
by using matrix, the build runs two parallel jobs, one for esp32 and
esp8266. with this, the build ends in 13 minutes
* use `PROJECT_` prefix for `export`ed environment variables to avoid
pollution in the build.
* enable cache in travis CI
* remove `~`, which is sometimes confusing (i.e. variable expansion)
you should use ${HOME} instead.
> ci: create build matrix

- components/ds1307/ds1307.c
I worked with ds1307 in and found, that the timer signal is configures incorrectly. The reason, turned out to be that the bit mask for the RS1:RS0 bits in the control register (0x07) sets incorrectly.
Other masks in this file look ok.
> ds1307: Fix SQWEF_MASK bit mask

- components/mcp23x17/mcp23x17.c
The MCP23S17 expects the 7-bit device address and a read/write bit
in the first byte of each transfer. Currently only the address is
sent. Fix this by shifting the address by one bit to the left and add
set the R/W bit if necessary.
> mcp23x17.c: Fix broken SPI device addressing

- components/ds1302/ds1302.c
- components/ds1307/ds1307.c
- components/ds3231/ds3231.c
- examples/ds1302/main/main.c
- examples/ds1307/main/main.c
- examples/ds3231/main/main.c
Fixes #76
This problem caused mktime to return wrong values
According to official (http://www.cplusplus.com/reference/ctime/tm/) documentation the tm structure is supposed to store year since 1900 instead of absolute year
> Fix incorrect implementation of tm structure

- components/sht3x/sht3x.c
When max uint32_t was reached, return value didn't overflow, but was kept at max uint32_t causing the SHT3x I2C device to abort reading measurement value (due to a check in sht3x_is_measuring function).
This was found using ESP8266_RTOS_SDK and the latest ESP8266 xtensa compiler. It might be different using ESP32...
Issue seems to exist a few more places in the esp-idf-lib (searching for gettimeofday usage), but I don't have the specific sensors, so I haven't made any modifications to those locations...
Best regards
Brian
> Bugfix for overflow issue in get_time_us function (sht3x.c).

- components/dht/dht.c
Found a bug on the DHT library related to using ESP_LOG inside a critical region.
This bug was already reported by other users:  #61 
Since ESP-IDF 4.xx this generates an abort: (https://github.com/espressif/esp-idf/issues/4412)
Fixed by exiting the critical region before printing. Did it on the macro because all the prints inside critical regions use the macro.
Tested the fix on ESP32.
Thanks for sharing this awesome library and best wishes!
> Bugfix for dht when tried to use ESP_LOG inside a critical region

- examples/bme680/main/main.c
Example not working otherwise. 
With this fix, the code suits the documentation on https://esp-idf-lib.readthedocs.io/en/latest/groups/bme680.html#measurement-cylce
> Fix bme680 example for check on bme680_get_results_float() fct

- README.md
- Adding guide to readme for using CMake FetchContent to have this lib fetched as part of cmake build
- Also notes in that section cmake minimum version becomes 3.11 if wanting to use this feature
> Guide to use CMake FetchContent

- .github/workflows/doc.yml
- docs/Makefile
- docs/requirements.txt
GitHub Actions was chosen because it is faster than Travis CI when
running CI in parallel.
fixes #113
> ci: build docs in GitHub Actions

- components/ultrasonic/ultrasonic.c
I've come across an issue where the timeout isn't firing for the ultrasonic component when going over the max distance. I think this is because `meas_timeout` is currently `echo_start + max_distance * ROUNDTRIP` which is then compared with `timeout_expired(echo_start, meas_timeout)`. This macro expands to:
```
((esp_timer_get_time() - (echo_start)) >= (echo_start + max_distance * ROUNDTRIP))
```
By removing the `echo_start` it should instead expand to:
```
((esp_timer_get_time() - (echo_start)) >= (max_distance * ROUNDTRIP))
```
> Remove additional start in ultrasonic timeout

- .github/workflows/build.yml
https://github.com/UncleRus/esp-idf-lib/runs/1448799077
Submodule path 'components/coap/libcoap': checked out 'cfec0d072c5b99ed3e54828ca50ea2f6b91e1f50'
Submodule 'ext/tinydtls' (https://git.eclipse.org/r/tinydtls/org.eclipse.tinydtls) registered for path 'components/coap/libcoap/ext/tinydtls'
Cloning into '/home/runner/work/esp-idf-lib/esp-idf-lib/idf/components/coap/libcoap/ext/tinydtls'...
Error: error: Server does not allow request for unadvertised object 3b24a701ed5b0785306aa732e739ecb1eb3d03f8
Fetched in submodule path 'components/coap/libcoap/ext/tinydtls', but it did not contain 3b24a701ed5b0785306aa732e739ecb1eb3d03f8. Direct fetching of that commit failed.
> bugfix: fetch all the history of submodules, fixes #134

- components/sht3x/sht3x.c
When periodic mode is configured, acquisition fails with :
SHT3x: Measurement is not started
This is because get_raw_data_nolock() resets 'meas_started' if 'mode'
is not correctly set.
Signed-off-by: Cédric Le Goater <clg@kaod.org>
> SHT3x: Fix periodic measurement

- components/mhz19b/mhz19b.h
even if we don't really need that much buffer space, a minimal value of 128
is required by the ESP32 at execution time.
> mzh19b: fix serial buffer length used by the driver

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/lint.yml
- .mdlrc
- .mdlstyle.rb
- .rubocop.yml
- CHANGELOG.md
- CONTRIBUTING.md
- FAQ.md
- Gemfile
- Gemfile.lock
- README.md
- components/bme680/README.md
- components/ccs811/README.md
- components/mhz19b/README.md
- components/sht3x/README.md
- examples/ads1115/README.md
- examples/ds3231/README.md
- examples/hd44780_i2c_scroll/README.md
- examples/led_effects/README.md
- examples/led_strip_spi/README.md
- examples/lm75/README.md
- examples/pca9685/README.md
- examples/tsl2561/README.md
- examples/tsl2591_interrupt/README.md
- examples/tsl2591_simple/README.md
fixes #192 
the implementation still has issues (issues in the upstream, or `mdl`). however, it is still better than nothing.
> ci: implement markdownlint

- .github/workflows/build.yml
this job is a meta job that requires all other build jobs. "Require
branches to be up to date before merging" in branch protection setting,
one needs to choose at least one test to pass. However, when the check
name is renamed, Pull Request is blocked because the new name is not
listed in the setting, and the repository admin needs to change the
setting everytime a test is renamed, added, or removed. This job can be
used for the test to pass.
> ci: add `all_build` job to build workflow

- components/ds18x20/ds18x20.c
- components/ds18x20/ds18x20.h
1. Refactor generic temperature read into model family specific reads to avoid having to read and cache the specific model number - just pass it DS18X20_ANY and be done with it.
2. Add scratchpad write and copy commands so you can modify the conversion config and save it to not have to reset it every boot.
> Ds18x20 improvements

- components/ccs811/ccs811.c
Corrected according to the [Adafruit Library](https://github.com/adafruit/Adafruit_CCS811/blob/8063146ace8b92ccd87475274db77be689229d5f/Adafruit_CCS811.cpp#L138).
Tested with actual sensor.
> Fixed ccs811 set environmental data

- components/led_strip/led_strip.c
- components/led_strip/led_strip.h
- components/mhz19b/mhz19b.c
The ESP-IDF version compatibility condition is referencing the wrong version. The struct parameters exist since v4.3.0, not 4.4.0. This PR fixes errors that otherwise arise from the parameters being undefined when using the libraries with ESP-IDF v4.3.0+.
For reference, you can see the parameters available in the docs:
- https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-reference/peripherals/uart.html#_CPPv413uart_config_t
- https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-reference/peripherals/rmt.html?highlight=rmt_translator_set_context#_CPPv426rmt_translator_set_context13rmt_channel_tPv
Tested the LED strip library working as it should.
> Parameters available in earlier version of ESP-IDF

- components/color/rgb.h
This fixes a minor compile error in rgb_invert
> color: fix narrowing conversion error

- .github/workflows/build.yml
fixed in 4.2, 4.3, and master
https://github.com/espressif/esp-idf/issues/7631#issuecomment-948445140
fixes #251
> ci: remove workaround for wrong CA bundle

- components/ds3231/ds3231.c
- components/ds3231/ds3231.h
I've extended the ds3231 module to set and get the aging offset register of an RTC.
> DS3231: set & get aging offset register

- components/led_strip_spi/led_strip_spi.c
The current led_strip_spi has incorrect pointer arithmetic for determining the starting memory address for each chunk, which this PR fixes.
Reproduction case: 
- ESP8266 with an led strip longer than 16 LEDs
- Set 1 LED to be a distinct colour from all others (i.e. red)
- Move the position of this distinct LED through all available positions
Symptom: Multiple LEDs will become red, or sometimes none, depending on the position of the LED. The symptom is consistent.
Cause: The SPI chunk sending code incorrectly calculates the address of subsequent chunks, because `i` is divided by `sizeof(uint32)`, but `strip->buf` is a void pointer, so addition to the address should be calculated in bytes.
This results in SPI sending each subsequent chunk starting from 16 bytes after the previous start …
> Bugfix: Fix pointer arithmetic for led_strip_spi for esp8266

- components/led_strip_spi/CMakeLists.txt
- components/led_strip_spi/led_strip_spi.c
error: initialized field overwritten [-Werror=override-init]
.data0_io_num = -1,
`data0_io_num` is a member of union (the other member is mosi_io_num),
and should not be initilized when `mosi_io_num` is initilized.
> led_strip_spi: fix "initialized field overwritten" error

- components/button/CMakeLists.txt
- components/color/CMakeLists.txt
- components/encoder/CMakeLists.txt
- components/hdc1000/CMakeLists.txt
- components/hmc5883l/CMakeLists.txt
- components/hts221/CMakeLists.txt
- components/hx711/CMakeLists.txt
- components/lib8tion/CMakeLists.txt
- components/mhz19b/CMakeLists.txt
- components/sht3x/CMakeLists.txt
- components/sht4x/CMakeLists.txt
- components/ultrasonic/CMakeLists.txt
- components/wiegand/CMakeLists.txt
> Added esp_timer to REQUIRES where needed

- .github/workflows/build.yml
by default, fail-fast is true. this means when one job in a matrix fails,
all other jobs in the matrix are canceled. this is not useful when you
want to know which job, or which combination of target, build_method,
and version, is failing. an example is #328.
https://github.com/UncleRus/esp-idf-lib/pull/328
see Handling failures at:
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
> ci: continue jobs even when a job in matrix fails

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
- CONTRIBUTING.md
the workflow labels PRs only. it does not create draft release notes.
later, another workflow will be added to generate draft release notes
after merging this.
see the discussion at:
https://github.com/UncleRus/esp-idf-lib/discussions/334
> ci: add pr-labeler GitHub Actions workflow

- .github/release-drafter.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
- CONTRIBUTING.md
this workflow generates a release draft when PRs with a label are merged
into `master` branch. a PR without a label, and a commit without PR,
will not be included in the draft.
as discussed at:
https://github.com/UncleRus/esp-idf-lib/discussions/334
> ci: introduce release-drafter GitHub Actions workflow

- .github/workflows/labeler.yml
PRs trigger both pull_request_target and pull_request, but the context
is different. as this workflow needs write access to PRs, pull_request
event does not work.
> ci: remove pull_request from labeler.yml

- .github/labeler.yml
when sync is `true`, labels are added or removed when PRs are modified.
> ci: sync labels in PRs

- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/metadata.yml
> ci: migrate CI to label-driven CI

- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/metadata.yml
when a labeler.yml add labels to a PR, that does not trigger other
workflows to prevent accidental recursive workflow runs. that means,
with the old implementation, when a member of the repository manually
add labels to a PR, all CI tests run as intended. however, when GitHub
Action bot (the workflow to label PRs) add labels, the `labeled` event
type will not trigger other CI tests.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
A workaround is to use Personal Access Token, as suggested the link
above. However, i do not like Personal Access Token because the token
represents a person, and the token must be updated if you follow the
advice from GitHub (they don't like a token without expiration).
instead, use workflow_run, …
> ci: trigger CI tests when "Label PR" completes

- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/labeler.yml
- .github/workflows/metadata.yml
the context other workflows triggered by workflow_run does not include
pull_requests objects.
pass the PR number from the triggering workflow, and get the PR using
an API, extract a list of labels from the response.
> ci: workaround empty pull_requests in workflow_run event

- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/labeler.yml
- .github/workflows/metadata.yml
this PR revert to `pull_request`-based CI as I originally wrote. the implementation in `master` branch does not behave like the previous one.
the PR supports with or without Personal Access Token. If the PAT is defined (`LABELER_TOKEN`), automatically assigned labels trigger CI tests. If not defined, fallback to `GITHUB_TOKEN`, and manual labeling is necessary to trigger CI tests.
> ci: revert to pull_request-based CI 

- FAQ.md
- docs/porting.md
I decided to write the how-to only. I think porting an I2C lib is a good exercise and I don't need the public API to lock and unlock port semaphores any longer.
> porting i2c libs

- components/ds3231/ds3231.c
- components/ds3231/ds3231.h
Becomes handy when suddenly the frequency is changed due to a power loss.
> Added ds3231_get_squarewave_freq

- examples/ads130e08/default/main/main.c
Improved the example for ads130e08 library, allowing the data to be read continuously with the use of a binary semaphore.
> improved example for ads130e08

- components/i2cdev/i2cdev.c
i2c_driver_install() needs to be called before i2c_param_config(). This fixes panic reported on [1].
Link: [1] https://github.com/espressif/esp-idf/issues/10163
Signed-off-by: Axel Lin <axel.lin@ingics.com>
> i2cdev: Fix i2c param config and driver install order for esp32 target

- README.md
- components/ads130e08/.eil.yml
- examples/ads130e08/default/README.md
Implementation of ads130e08 driver validated on ESP32S3 board.
> added esp32s3 support for ads130e08

- components/encoder/encoder.c
When using BTN_PRESSED_LEVEL 1 (CONFIG_RE_BTN_PRESSED_LEVEL_1=y) the input pins should be pulled down instead of up. 
Also explicitly configured the opposite setting for clarity
> Encoder: properly configure pin when using BTN_PRESSED_LEVEL = 1

- components/mcp23x17/mcp23x17.c
The mcp23x17.h file defines a function called mcp23x17_free_desc_spi, but the corresponding implementation in the mcp23x17.c file referred to it as mcp23x17_free_desc.
> Update function name in mcp23x17.c to match the one in the header

- components/mcp23x17/mcp23x17.c
According to the MCP23S17 data sheet:
> The Open-Drain (ODR) control bit enables/disables the INT pin for open-drain configuration. Setting this bit overrides the INTPOL bit. The Interrupt Polarity (INTPOL) sets the polarity of the INT pin. This bit is functional only when the ODR bit is cleared, configuring the INT pin as active push-pull.
This PR proposes to clear the ODR bit if INTPOL gets set.
> Ensure the ODR bit is cleared before setting the INTPOL bit.

- components/i2cdev/i2cdev.c
Fix for issue #501 
I tested it on my 8266 Development board with PCA9685 and MPU6050.
`i2c_setup_port()` stopped reconfiguring for every i2c read or write, which I believe impacts positively performance on this platform.
> fix for issue #501 - comparing i2c configuration on 8266

- .github/workflows/ci.yml
Fix CI builds for ESP32xx does not properly mark as failed
> chore: fix esp32 ci exit code

- components/lsm303/lsm303.c
- components/lsm303/lsm303.h
- examples/lsm303/default/main/main.c
I have fixed ODR enum names and removed static specifier conversion arrays
> fix: lsm303 ODR names and non-static scale arrays

- components/ina219/ina219.c
> ina219: fix bus voltage measuring

- components/esp_idf_lib_helpers/esp_idf_lib_helpers.h
Allows building for the ESP32-H2 chip. I tried it with a couple sensors and it seems to work fine.
> Add support for H2 chip

- README.md
- components/pca9557/.eil.yml
- components/pca9557/pca9557.c
- components/pca9557/pca9557.h
The `pca9557` driver works well with PCA9536 but needs its i2c address in `pca9557_init_desc`
> feat: add PCA9536 support

- components/sht4x/sht4x.c
Fix for https://github.com/UncleRus/esp-idf-lib/issues/598
> SHT4x often gives "i2cdev: Could not read from device [0x44 at 0]" error on measurement #598 fix

- components/ina219/ina219.c
- components/ina219/ina219.h
- examples/ina219/default/main/Kconfig.projbuild
- examples/ina219/default/main/main.c
> fix: remove unused parameter in ina219_calibrate()

- components/bme680/bme680.c
> fix: fix negative temperature readings in bme680

- components/hx711/hx711.c
> fix: reset gpio before use in hx711

- components/ultrasonic/ultrasonic.c
- components/ultrasonic/ultrasonic.h
This commit introduces temperature compensation to the ultrasonic sensor distance measurement functions, enhancing accuracy across a range of environmental conditions. The speed of sound varies with air temperature, impacting the precision of ultrasonic distance measurements.
Changes include:
- Added `ultrasonic_measure_temp_compensated` function for temperature-compensated distance measurements in meters.
- Added `ultrasonic_measure_cm_temp_compensated` function for temperature-compensated distance measurements in centimeters.
- Defined `SPEED_OF_SOUND_AT_0C_M_S` macro to replace the magic number 331.4, clarifying the code and facilitating future adjustments.
- Updated the `ultrasonic.h` header file to include prototypes for the new functions, alongside detailed comments explaining their …
> Add temperature compensation to ultrasonic distance measurements

- components/mcp23x17/mcp23x17.c
- components/mcp23x17/mcp23x17.h
* This is useful when multiple devices, with a different addresses, are sharing the same CS line on the SPI bus.
> Allow using software controlled Chip Select (CS) for MCP23S17.

- components/encoder/Kconfig
- components/encoder/encoder.c
- components/encoder/encoder.h
- examples/encoder/default/main/main.c
Improve rotary "tick". Misses less ticks.
Add Acceleration for rotary encoder with the following functions to enable or disable acceleration. The larger the Coefficient, the faster the acceleration.
```
esp_err_t rotary_encoder_enable_acceleration(rotary_encoder_t *re, uint16_t coeff)
esp_err_t rotary_encoder_disable_acceleration(rotary_encoder_t *re)
```
Added 2 configurable time variables to Kconfig:
```
config RE_ACCELERATION_MIN_CUTOFF
int "Minimum Acceleration cutoff time (ms)"
default 200
help
At this time in milliseconds between rotary ticks we want to be at the minimum acceleration
config RE_ACCELERATION_MAX_CUTOFF
int "Maximum Acceleration cutoff time (ms)"
default 4
help
At this time in milliseconds between rotary ticks we want to be at the maximum acceleration
```
to determine …
> Improve Rotary Encoder

- README.md
- devtools/devtool/templates/README.md
Added ads130e08 to the excluded components for the ESP8266 RTOS SDK Makefile
> doc: Update README.md ESP8266 EXCLUDE_COMPONENTS

- components/ds3502/ds3502.c
should be less than max value, not greater than.  In its current state it rejects all valid messages.
> ds3502 set function check for max value has wrong comparison

- examples/ds3502/default/main/main.c
address and port positions in example init function were out of place
> variables swapped in ds3502 example

- components/hx711/hx711.c
Utilizing BIT64() instead of BIT() in hx711 component as BIT is only for 32 bit, hence using any PINs above 31 becomes a problem.
> Amend: Use BIT64() instead of BIT() to accommodate PINS >= 32

- components/i2cdev/.eil.yml
- components/i2cdev/CMakeLists.txt
- components/i2cdev/Kconfig
- components/i2cdev/component.mk
- components/i2cdev/i2cdev.c
- components/i2cdev/i2cdev.h
- components/i2cdev/i2cdev_legacy.c
Migrate i2cdev to new ESP-IDF I2C master driver API (v5.3+)
- Replace legacy command-based I2C with handle-based master API for ESP-IDF v5.3 and newer.
- Add device handle tracking and automatic resource cleanup  
- Enhance addressing support (7-bit/10-bit) and error handling
- Implement smart retry logic with exponential backoff
- Add buffer overflow protection and memory optimization
- Full Backward Compatibility
- **Drop-in replacement** for existing sensor drivers
- Legacy compatibility maintained in `i2cdev_legacy.c`
- Automated Build-Time Driver Selection - build system automatically detects the ESP-IDF version and selects the appropriate driver (modern or legacy).
- Manual Override: A Kconfig option (I2CDEV_USE_LEGACY_DRIVER) to force the use of the legacy driver on any platform.
- …
> feat: migrate i2cdev to new ESP-IDF I2C master driver API
