- components/bmp280/bmp280.c
When using 'FORCED' mode, initial reading of 'measuring' bit from status register seems to be 0 and switches to 1 only after some time. This may lead to incorrect determination of measurement complete state.
It seems more reliable to always treat FORCED mode as busy state, since device automatically switches to SLEEP mode after performing measurement.
Patch contains corresponding modification to bmp280_is_measuring() function for this purpose.
> BMP280: bmp280_is_measuring fix - checking for FORCED mode

- components/hd44780/hd44780.c
Hi.
Thank you for providing these libraries.
I am using the code with a 20x04 display with a compatible controller (SPLC780D) and GPIOs on an ESP32.
Initializing the controller for two-line mode failed consistently until I found that the code did not pause between the "select 4 bit mode" and "selæect number of lines" commands.
Furthermore I adjusted the bit-banging in write_nibble():
According to the datasheet (https://www.sparkfun.com/datasheets/LCD/HD44780.pdf) figure 25 on page 58 there should be a delay between setting RS and asserting E.
Also the DELAY_TOGGLE of 10μs is much larger than required by the datasheet (E cycle time >= 1μs, E pulse width >= 450ns, Data set-up time >= 195ns) so I lowered it to 1μs.
(Since I do not have a I2C-expander present I have not adjusted the RS/E …
> Add missing delay after selecting 4 bit mode.

- components/hd44780/hd44780.c
- components/max7219/max7219.h
> Fix make error

- components/hd44780/hd44780.c
- components/hd44780/hd44780.h
- examples/hd44780_i2c_scroll/CMakeLists.txt
- examples/hd44780_i2c_scroll/Makefile
- examples/hd44780_i2c_scroll/README.md
- examples/hd44780_i2c_scroll/main/CMakeLists.txt
- examples/hd44780_i2c_scroll/main/component.mk
- examples/hd44780_i2c_scroll/main/main.c
> hd44780: implement scroll functions

- .github/ISSUE_TEMPLATE/bug_report.md
- .travis.yml
- README.md
- components/ds1302/ds1302.c
- components/esp_idf_lib_helpers/esp_idf_lib_helpers.h
- components/hd44780/hd44780.c
> support esp-idf 3.3.x

- .github/ISSUE_TEMPLATE/driver_request.md
> doc: add a template for new driver request

- .travis.yml
> bugfix: update python to 3.x and adopt newer installation procedure

- components/hmc5883l/hmc5883l.c
- components/hx711/hx711.c
- components/sht3x/sht3x.c
- components/sht3x/sht3x.h
This PR replaces `gettimeofday()` usage `with esp_timer_get_time()`
> Fixes #118

- components/bme680/bme680.c
- components/bme680/bme680.h
> fix bme680 pressure calculation

- .github/workflows/build.yml
- examples/ads1115/main/main.c
- examples/bh1750/main/main.c
- examples/bme680/main/main.c
- examples/bmp180/main/main.c
- examples/bmp280/main/main.c
- examples/hmc5883l/main/main.c
- examples/lm75/main/main.c
- examples/max31725/main/main.c
- examples/max7219_7seg/main/main.c
- examples/max7219_8x8/main/main.c
- examples/mcp342x/main/main.c
- examples/mcp9808/main/main.c
- examples/ms5611_i2c/main/main.c
- examples/pca9685/main/main.c
- examples/pcf8591/main/main.c
- examples/qmc5883l/main/main.c
- examples/sht3x/main/main.c
- examples/si7021/main/main.c
- examples/tsl2561/main/main.c
- examples/tsl4531/main/main.c
> ci: build examples with esp32s2

- components/led_strip_spi/led_strip_spi.c
> led_strip_spi: send 512 bytes SPI data at a time

- .github/workflows/build.yml
- .github/workflows/doc.yml
> ci: introduce build_esp8266_v3_x, skip-duplicate-actions GitHub Actions

- .github/workflows/build.yml
> ci: support ESP8266 v3.3

- CHANGELOG.md
- components/led_strip/led_strip.c
@trombik What do you think of the CHANGELOG format?
And I might be missing something, could you please check?
> Release 0.8.0

- .github/workflows/lint.yml
- CONTRIBUTING.md
- examples/example/README.md
> ci: fix clang-format check in Pull Request

- .github/workflows/build.yml
> ci: bump 4.0.x version to 4.0.4

- .github/workflows/build.yml
this is the last release of v3.3.x
> ci: update v3.3.x to v3.3.6

- .github/workflows/build.yml
> ci: update v4.2.x branch to 4.2.3

- components/bmp180/bmp180.c
- components/dht/dht.c
- components/ds1302/ds1302.c
- components/esp_idf_lib_helpers/ets_sys.h
- components/hd44780/hd44780.c
- components/hx711/hx711.c
- components/led_strip/led_strip.c
- components/ms5611/ms5611.c
- components/onewire/onewire.c
- components/pca9685/pca9685.c
- components/scd4x/scd4x.c
- components/sgp40/sgp40.c
- components/ultrasonic/ultrasonic.c
> moved ets_sys.h includes to seperate file

- .github/workflows/labeler-by-workflow-status.yml
see the discussion at:
https://github.com/UncleRus/esp-idf-lib/discussions/365
> ci: add a labeler to label PRs by workflow conclusion

- .github/workflows/labeler-by-workflow-status.yml
the script argument is javascript code, and `#` should not be used as
comment.
> ci: fix comments

- .github/workflows/actions-on-pr-by-label.yml
this workflow can be used to take actions when a label is added to PRs.
> ci: introduce Actions on PR by label workflow

- .github/labeler.yml
- .github/workflows/README.md
- CONTRIBUTING.md
this docuemnt is for CI maintainers. another commit will add
explanations for users.
requested in https://github.com/UncleRus/esp-idf-lib/discussions/365#discussioncomment-3019912
> doc: document how workflows are designed

- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/metadata.yml
otherwise, CI will not run because PRs cannot be `master` branch.
> ci: do not filter CI by branches

- .github/workflows/README.md
- .github/workflows/actions-on-pr-by-label.yml
- .github/workflows/labeler-by-workflow-status.yml
- .github/workflows/labeler.yml
> ci: document Personal Access Token for automation

- .github/workflows/build.yml
- components/led_strip_spi/led_strip_spi.c
> ci: udpate to esp-idf v4.3.3

- .github/workflows/actions-on-pr-by-label.yml
> ci: fix invalid syntax in a workflow

- .github/workflows/doc.yml
related issue: #406
this might, or might not, fix the related issue
> ci: update actions/checkout to v2

- .github/workflows/actions-on-pr-by-label.yml
the object is dict, not a list
> ci: fix permissions in actions-on-pr-by-label.yml

- Metadata.md
> doc: reorder Usages of metadata in the project section

- .github/workflows/build.yml
also:
* remove unused variables from master branch build
* update python to 3.10
> ci: update esp-idf to 4.4.2

- components/max7219/max7219.c
> Fix max7219 string bounds check

- .github/workflows/README.md
- .github/workflows/action-check-components-and-examples.yml
- .github/workflows/action-check-components-label.yml
- .github/workflows/build.yml
- .github/workflows/doc.yml
- .github/workflows/labeler.yml
- .github/workflows/metadata.yml
> ci: update actions/checkout to v3

- components/esp_idf_lib_helpers/ets_sys.h
> bugfix: fix ets_sys.h error

- .github/workflows/build.yml
> bugfix: add esp-idf 5.x build to CI

- components/hx711/hx711.c
> Fix signed division of HX711 average read

- components/tsl2591/tsl2591.c
- components/tsl2591/tsl2591.h
- examples/tsl2591/default/main/main.c
> fix: add sensor init to default tsl2591 example

- components/i2cdev/i2cdev.c
> fix: workaround in i2cdev for #501

- examples/mcp23x17/mcp23017/main/main.c
> fix: fix example for mcp23017

- CONTRIBUTING.md
> doc: document our default policy about targets

- components/lm75/lm75.c
> lm75: fix reading negative temperatures
